# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lplex < Formula
  desc "CAN bus HTTP bridge for NMEA 2000"
  homepage "https://github.com/sixfathoms/lplex"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sixfathoms/lplex/releases/download/v0.1.1/lplex_0.1.1_darwin_amd64.tar.gz"
      sha256 "f2054f18b36d41b83f289652e85878679dd6a9bf56f69c69de4b805ae49600e6"

      define_method(:install) do
        bin.install "lplex"
        bin.install "lplexdump"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sixfathoms/lplex/releases/download/v0.1.1/lplex_0.1.1_darwin_arm64.tar.gz"
      sha256 "92ccb8747d33e8bbe277a5d67da02dae418f26308a72b74c93ba8f18b186c8f5"

      define_method(:install) do
        bin.install "lplex"
        bin.install "lplexdump"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sixfathoms/lplex/releases/download/v0.1.1/lplex_0.1.1_linux_amd64.tar.gz"
      sha256 "c2a09823b83c2dd29ede251ca2f3cdb019740fcb1e44f21f99f03470bcb0f033"
      define_method(:install) do
        bin.install "lplex"
        bin.install "lplexdump"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sixfathoms/lplex/releases/download/v0.1.1/lplex_0.1.1_linux_arm64.tar.gz"
      sha256 "f4fe477cfd3cc1f0bf79aab4e70cf7d7b04f1152d083a8471b8327dbd8463828"
      define_method(:install) do
        bin.install "lplex"
        bin.install "lplexdump"
      end
    end
  end
end
