# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lplexdump < Formula
  desc "NMEA 2000 CAN bus streaming client"
  homepage "https://github.com/sixfathoms/lplex"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sixfathoms/lplex/releases/download/v0.1.2/lplexdump_0.1.2_darwin_amd64.tar.gz"
      sha256 "f190f4a6855f2cd3baf6d21e4eb124dcbc85252f98c2615d4d8d2a55ac0a7bb7"

      define_method(:install) do
        bin.install "lplexdump"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sixfathoms/lplex/releases/download/v0.1.2/lplexdump_0.1.2_darwin_arm64.tar.gz"
      sha256 "cfd0308d67a2c189870bb00e019f617047445f65231ec226f7422776064c0353"

      define_method(:install) do
        bin.install "lplexdump"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sixfathoms/lplex/releases/download/v0.1.2/lplexdump_0.1.2_linux_amd64.tar.gz"
      sha256 "78dc8fff387a5482ea1d9ad47461c092b8ebeef40e1a4e533b69cd52733b92e1"
      define_method(:install) do
        bin.install "lplexdump"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sixfathoms/lplex/releases/download/v0.1.2/lplexdump_0.1.2_linux_arm64.tar.gz"
      sha256 "fe99a46893bc0ddda901c38e1d6ada642512a522999487483bcb6b86d40151b1"
      define_method(:install) do
        bin.install "lplexdump"
      end
    end
  end
end
