# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lplex < Formula
  desc "NMEA 2000 CAN bus multi-tool CLI"
  homepage "https://github.com/sixfathoms/lplex"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sixfathoms/lplex/releases/download/v0.4.1/lplex_0.4.1_darwin_amd64.tar.gz"
      sha256 "1282e1a6ff21aec3e00ea5613321b550d60c500687add3f6706b9c36c5485f6f"

      define_method(:install) do
        bin.install "lplex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sixfathoms/lplex/releases/download/v0.4.1/lplex_0.4.1_darwin_arm64.tar.gz"
      sha256 "71e4f5937ff7f15aeffc6d1417bc6c7fecd139025fc9e5a56405cb97512345b7"

      define_method(:install) do
        bin.install "lplex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sixfathoms/lplex/releases/download/v0.4.1/lplex_0.4.1_linux_amd64.tar.gz"
      sha256 "3735b889cdfbc915eda6d24b2bc485d609949de7eb9c9fe5a0b74c73bc0210d8"
      define_method(:install) do
        bin.install "lplex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sixfathoms/lplex/releases/download/v0.4.1/lplex_0.4.1_linux_arm64.tar.gz"
      sha256 "09392a42fba41b4943dac7a0821b617582c72dfef520b38838228b383423d0a5"
      define_method(:install) do
        bin.install "lplex"
      end
    end
  end
end
